version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: foss-website-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: foss_website
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - foss_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: foss-website-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - foss_network

networks:
  foss_network:
    driver: bridge

volumes:
  postgres_data: